repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: npx prettier --write "./app/**/*.{js,ts,css}"
        language: system
        files: \.js$|\.ts$|\.css$

  - repo: https://github.com/pycqa/pytest
    rev: v7.1.2
    hooks:
      - id: pytest