name: "setup-rules-engine"
description: "Sets up the environment for the rules engine"
inputs:
  python-version:
    description: Python version to use (e.g. "3.10")
    required: true
  working-directory:
    description: The working directory for the rules engine
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -e .